name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: eConan ejecuta las pruebas
      id: econan-ejecuta-las-pruebas
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: eConan ejecuta las pruebas
        setup-command: ''
        command: gradle check
        timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ECONAN-EJECUTA-LAS-PRUEBAS_RESULTS: "${{steps.econan-ejecuta-las-pruebas.outputs.result}}"
      with:
        runners: econan-ejecuta-las-pruebas
